### ISSUE TITLE
Restore WORKSPACE support

### ISSUE THREAD

**Issue by alexeagle** [theoremlp/rules_multitool#11]
It's awesome to have bzlmod support here now!

I'd like to use this to simplify how rules_lint was forcing users to fetch tools, see https://github.com/aspect-build/rules_lint/pull/161

However rules_lint still supports users on both WORKSPACE and bzlmod.

From
https://github.com/theoremlp/rules_multitool/blob/main/multitool/extension.bzl#L18
I think the underlying repository rule is now a private API, so I think we need to add something back to allow WORKSPACE users to create a functioning `@multitool` repo.

**Comment by mark-thm** [comment]
You can still call the `multitool` repository rule from WORKSPACE (it's exposed in https://github.com/theoremlp/rules_multitool/blob/main/multitool/multitool.bzl), see the example here: https://github.com/theoremlp/rules_multitool/blob/main/examples/target-determinator/WORKSPACE.bazel

**Comment by alexeagle** [comment]
Yes of course, I should have checked the example - thanks!
