### ISSUE TITLE
Tools are registered for both exec and target platform

### ISSUE THREAD

**Issue by alexeagle** [theoremlp/rules_multitool#17]
That declaration is here:
https://github.com/theoremlp/rules_multitool/blob/main/multitool/private/hub_repo_tool_template/tool.bzl.template#L27-L34

My (poor) understanding is that this is incorrect - it means this toolchain will be selected if the exec platform matches the constraints, then used on the target platform, and vice versa. When exec != target we ought to be able to reproduce that a wrong tool is used.

(Probably we could make a test case here where we package target-determinator inside a linux_arm64 docker container, and when we build it on CI we would get an x86 binary instead since that's the execution platform)

For rules_py, we decide ahead-of-time whether a tool is run in an action or on the target: https://github.com/aspect-build/rules_py/blob/main/py/private/toolchain/tools.bzl#L6-L12
and pass that to the template
https://github.com/aspect-build/rules_py/blob/main/py/private/toolchain/repo.bzl#L36-L43
but that doesn't work here since the person declaring the tools lockfile may not know how an end-user plans to run it.

One answer is to register two toolchains for each tool, one for each platform.
Here's a long thread about it: https://bazelbuild.slack.com/archives/CDCMRLS23/p1705983174289549?thread_ts=1705950771.810849&cid=CDCMRLS23

**Comment by mark-thm** [comment]
Ah sure. We don’t do any cross compiling right now — rules_python provides little help and converting to using rules_pycross is a deep backlog item — so haven’t noticed this. 

Happy to duplicate the toolchain defs, that’s a pretty narrow change.

**Comment by mark-thm** [comment]
I'll cut another release after the [last one merges in BCR](https://github.com/bazelbuild/bazel-central-registry/pull/1598)
