### ISSUE TITLE
support windows

### ISSUE THREAD

**Issue by peakschris** [theoremlp/rules_multitool#44]
I am working on some windows issues for rules_lint, and it seems that one of the challenges is that rules_multitool, used in rules_lint, doesn't support windows, so we can't add dependencies on windows binaries. What would be involved in supporting windows as a platform?

**Comment by mark-thm** [comment]
we’re not windows users and don’t have windows test environments, so I can’t speak to a full set of things that you’ll run into. At a minimum:
 - the need platform set would need to include Windows: https://github.com/theoremlp/rules_multitool/blob/28cac8ed2495bce3550318ba6e3d661534121e45/multitool/private/multitool.bzl#L49
 - the schema for the lockfile will need to be updated accordingly (and the multitool CLI similarly updated
 - this ruleset depends on Bazel’s symlink action
 - the cwd targets assume presence of bash

**Comment by peakschris** [comment]
Thanks! I'll give this a go and create a PR.

> this ruleset depends on Bazel’s symlink action, unclear if/how that’s handled on Windows

bazel symlink action works fine if `startup --windows_enable_symlink` is used. If not, bazel does a copy inside this API. We can require symlinks, I don't know why anyone would not use them in current windows versions.

> the cwd targets assume presence of bash, unclear if you’d need a different approach on Windows

We are already dependent on bash for many things, it's hard to run bazel on windows without it. Bash can be a prerequisite.

**Comment by peakschris** [comment]
I have created https://github.com/theoremlp/rules_multitool/pull/45, I hope this can be considered once I've ironed out the bugs. Any help you can offer in suggesting improvements would be awesome.

**Comment by mark-thm** [comment]
#45 has merged, I'd be grateful if you could take the most recent commit for a spin in a repo of yours somewhere just to validate everything is functional before I cut a full release.

**Comment by peakschris** [comment]
@mark-thm it's working nicely, thank you again!
